eval "$(/opt/homebrew/bin/brew shellenv)"
export PATH="$HOME/.jenv/bin:$PATH"
export STARSHIP_CONFIG="$HOME/.config/starship/config.toml"
export STARSHIP_CACHE="$HOME/.config/starship/cache"
export DOTFILES="$HOME/.dotfiles"
